---
- name: Install apache2
  apt: package=apache2 state=installed force=yes update_cache=yes
  tags:
      - apache2_install
      - apache2

- name: Enable required apache2 modules
  apache2_module: state=present name={{ item }}
  with_items:
            - proxy
            - proxy_ajp
            - proxy_balancer
            - proxy_http
            - lbmethod_byrequests
            - setenvif
            - mime
            - socache_shmcb
            - ssl
  tags:
      - apache2_enable_mods
      - apache2

- name: Copy the domain template
  template: src=domain.j2  dest=/etc/apache2/sites-available/{{ domain_name }}.conf owner=root group=root mode=0644
  tags:
      - apache2_domain
      - apache2

- name: Add hybris hosts in host file
  lineinfile: "dest=/etc/hosts state=present regexp='^{{ item.ip }} ' line='{{ item.ip }} {{ item.name }}'"
  with_items:
            - '{{ servers_list }}'
  when: item.type == 'adm' or item.type == 'app'
  tags:
      - hybris_add_hosts
      - hybris

- name: Enable the domain
  shell: "a2ensite {{ domain_name }}.conf"
  notify:
        - Restart apache2
  tags:
      - apache2_domain
      - apache2
