- name: Chown Hybris Dir
  file: path=/opt/{{ hybris_version }} state=directory owner=hybris group=hybris mode=0775
  tags:
      - hybris_chown
      - hybris

- name: Chown NFS Dir
  file: path=/var/nfs/ state=directory owner=hybris group=hybris mode=0775
  when: servers_list[0].type == 'adm'
  tags:
      - nfs_chown
      - nfs
