---
- name: Install nfs client
  apt: name=nfs-common state=present update_cache=yes
  tags:
      - nfs_client_install
      - nfs

- name: Create nfs share folder
  file: path=/var/nfs owner=hybris group=hybris mode=0775 state=directory
  tags:
      - nfs_share_folder
      - nfs

- name: Mount nfs
  mount: path=/var/nfs/ src={{ servers_list[0].ip }}:/var/nfs state=mounted fstype=nfs4 opts=rw,hard,noatime,nolock,tcp,intr
  tags:
      - nfs_mount
      - nfs
