---
- name: Install nfs client
  apt: name=nfs-common state=present update_cache=yes
  tags:
      - nfs_client_install
      - nfs

- name: Create nfs share folder
  file: path=/var/nfs owner=hybris group=hybris mode=0775 state=directory
  tags:
      - nfs_share_folder
      - nfs

- name: Mount nfs
  shell: 'mount {{ servers_list[0].ip }}:/var/nfs /var/nfs/'
  tags:    
      - nfs_mount
      - nfs

- name: Automatically mount the NFS share during the OS startup
  lineinfile: "path=/etc/fstab owner=root group=root mode=0775 regexp='^{{ item.ip }}:/var/nfs ' line='{{ item.ip }}:/var/nfs  /var/nfs  nfs      auto,noatime,nolock,bg,nf svers=3,intr,tcp,actimeo=1800 0 0'"
  with_items:
            - '{{ servers_list }}'
  when: item.type == 'app'
  tags:
      - nfs_export_config
      - nfs  
