---
- name: Install nfs client
  apt: name=nfs-common state=present update_cache=yes
  tags:
      - nfs_client_install
      - nfs

- name: Mount nfs
  shell: '{{ item }}'
  with_items:
            - 'mkdir -p /mnt/nfs/var/nfs'
            - 'mount servers_list[0].ip:/var/nfs /mnt/nfs/var/nfs/'
  tags:
      - nfs_mount
      - nfs
